[versions]
kotlin = "2.2.20"
shadow = "9.3.1"
architectury-loom = "1.13-SNAPSHOT"
architectury-plugin = "3.4-SNAPSHOT"
minecraft = "1.21.1"
fabric-loader = "0.17.2"
fabric-api = "0.116.6+1.21.1"
fabric-permissions-api = "0.3.1"
neoforge = "21.1.182"
junit = "5.1.0"
publish = "0.35.0"
sponge-mixin = "0.8.5"
faststats = "0.29.4"
emberstextapi = "3.0.0"
modmenu = "v6Xx3fbU"
luckperms = "5.4"
luckperms-fabric = "6h9SnsZu" # v5.4.150 Fabric (https://modrinth.com/plugin/luckperms/version/v5.4.150-fabric)
luckperms-neoforge = "dKAPoPGd" # v5.4.150 NeoForge (https://modrinth.com/plugin/luckperms/version/v5.4.150-neoforge)
sqlite-jdbc = "3.53.2.0"
sqlite-mod = "EEE7nXWy" # 3.53.2.0+2026-06-06
mysql-connector-j = "9.7.0"
mysql-mod = "XiFojYbi" # 9.7.0+2026-05-03
impactor-fabric = "5.3.5+1.21.1-Fabric-fabric,1.21.1"
impactor-neoforge = "5.3.5+1.21.1-Neoforge-neoforge,1.21.1"
adventure-key = "4.13.0"
adventure-mod = "6.0.0"
adventure-api = "4.17.0"
forge-config-api-port = "21.1.6"
team-reborn-energy = "4.1.0"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
architectury-loom = { id = "dev.architectury.loom", version.ref = "architectury-loom" }
architectury-plugin = { id = "architectury-plugin", version.ref = "architectury-plugin" }

[libraries]
publish = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version.ref = "publish" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
architectury-loom = { group = "dev.architectury", name = "architectury-loom", version.ref = "architectury-loom" }
architectury-plugin = { group = "architectury-plugin", name = "architectury-plugin.gradle.plugin", version.ref = "architectury-plugin" }
shadow-gradle = { group = "com.gradleup.shadow", name = "shadow-gradle-plugin", version.ref = "shadow" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
minecraft-net = { group = "net.minecraft", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-permissions-api = { group = "me.lucko", name = "fabric-permissions-api", version.ref = "fabric-permissions-api" }
neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge" }
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
sponge-mixin = { group = "org.spongepowered", name = "mixin", version.ref = "sponge-mixin" }
faststats = { group = "dev.matthiesen.libs", name = "faststats", version.ref = "faststats" }
emberstextapiFabric = { group = "net.tysontheember.emberstextapi", name = "emberstextapi-fabric-1.21.1", version.ref = "emberstextapi" }
emberstextapiNeoForge = { group = "net.tysontheember.emberstextapi", name = "emberstextapi-neoforge-1.21.1", version.ref = "emberstextapi" }
modmenu = { group = "maven.modrinth", name = "mOgUt4GM", version.ref = "modmenu" }
impactor-fabric = { group = "maven.modrinth", name = "impactor", version.ref = "impactor-fabric" }
impactor-neoforge = { group = "maven.modrinth", name = "impactor", version.ref = "impactor-neoforge" }
adventure-key = { group = "net.kyori", name = "adventure-key", version.ref = "adventure-key" }
luckperms-api = { group = "net.luckperms", name = "api", version.ref = "luckperms" }
luckperms-fabric = { group = "maven.modrinth", name = "luckperms", version.ref = "luckperms-fabric" }
luckperms-neoforge = { group = "maven.modrinth", name = "luckperms", version.ref = "luckperms-neoforge" }
sqlite-jdbc = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite-jdbc" }
sqlite-mod = { group = "maven.modrinth", name = "bTTf2DEw", version.ref = "sqlite-mod" }
mysql-connector-j = { group = "com.mysql", name = "mysql-connector-j", version.ref = "mysql-connector-j" }
mysql-mod = { group = "maven.modrinth", name = "2UdFEObs", version.ref = "mysql-mod" }
adventure-mod-shared = { group = "net.kyori", name = "adventure-platform-mod-shared", version.ref = "adventure-mod" }
minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure-api" }
text-serializer = { group = "net.kyori", name = "adventure-text-serializer-json", version.ref = "adventure-api" }
forge-config-api-port-common = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-common-neoforgeapi", version.ref = "forge-config-api-port" }
forge-config-api-port-fabric = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-fabric", version.ref = "forge-config-api-port" }
team-reborn-energy = { group = "teamreborn", name = "energy", version.ref = "team-reborn-energy" }

[bundles]
commonCompileOnly = ["sponge-mixin", "luckperms-api", "minimessage", "text-serializer", "sqlite-jdbc", "mysql-connector-j", "forge-config-api-port-common"]
commonImplementation = ["faststats", "adventure-key"]
commonModCompileOnly = ["emberstextapiFabric", "impactor-fabric", "adventure-mod-shared"]
commonModImplementation = []
commonModImplementationNoTransitive = []

fabricCompileOnly = []
fabricImplementation = ["faststats"]
fabricModCompileOnly = ["fabric-permissions-api", "emberstextapiFabric", "impactor-fabric", "luckperms-fabric"]
fabricModApi = ["forge-config-api-port-fabric", "team-reborn-energy"]
fabricModRuntimeOnly = ["emberstextapiFabric", "modmenu", "sqlite-mod", "mysql-mod", "forge-config-api-port-fabric"]
fabricModImplementation = ["fabric-loader", "fabric-api"]
fabricModImplementationNoTransitive = []

neoforgeCompileOnly = []
neoforgeImplementation = ["faststats"]
neoforgeModCompileOnly = ["emberstextapiNeoForge", "impactor-neoforge", "luckperms-neoforge"]
neoforgeModRuntimeOnly = ["emberstextapiNeoForge", "sqlite-mod", "mysql-mod"]
neoforgeModImplementation = []
neoforgeModImplementationNoTransitive = []