modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "${github_url}/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
logoFile = "icon.png"

[[mixins]]
config = "matthiesen_core.mixins.json"

[[mixins]]
config = "matthiesen_core_neoforge.mixins.json"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.182,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "emberstextapi"
type = "optional"
mandatory = false
versionRange = "[3.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "impactor"
type = "optional"
mandatory = false
versionRange = "[5.3.5+1.21.1,)"
ordering = "AFTER"
side = "SERVER"

[[dependencies.${mod_id}]]
modId = "luckperms"
type = "optional"
mandatory = false
versionRange = "[5.4,)"
ordering = "AFTER"
side = "SERVER"

[[dependencies.${mod_id}]]
modId = "adventure_platform_neoforge"
type = "optional"
mandatory = false
versionRange = ""
ordering = "AFTER"
side = "SERVER"

[[dependencies.${mod_id}]]
modId = "mysql_jdbc"
type = "optional"
mandatory = false
versionRange = "[9.7.0+2026-05-03,)"
ordering = "AFTER"
side = "SERVER"

[[dependencies.${mod_id}]]
modId = "sqlite_jdbc"
type = "optional"
mandatory = false
versionRange = "[3.53.2.0+2026-06-06,)"
ordering = "AFTER"
side = "SERVER"
